#!/bin/bash

target="vimrc-single-file"

cat vimrc > $target

for f in configuration/single-file/* configuration/used/*; do
    case $f in
        *plugin-configuration*|*private*)
            echo skipping $f >&2
        ;;
        *)
            echo -e "\n\n\" ====== $f ======\n" >> $target
            cat $f >> $target
        ;;
    esac
done
