#!/bin/bash

ferr(){
    echo "FATAL ERROR: $*"
    exit 1
}

disable_all(){
    rm -f \
        ~/.vim/pack/plugins/start/git-supertab \
        ~/.vim/pack/plugins/start/git-YouCompleteMe \
        ~/.vim/plugin/plugin-configuration-you-complete-me.vim \
        ~/.vim/pack/plugins/start/git-coc.nvim \
        ~/.vim/plugin/plugin-configuration-coc.vim
}

enable_ycm(){
    cd ~/.vim/pack/plugins/start || ferr "can not cd"
    ln -s ../bundle-available-github/supertab git-supertab || ferr

    cd ~/.vim/pack/plugins/start || ferr "can not cd"
    ln -s ../bundle-available-github/YouCompleteMe git-YouCompleteMe || ferr

    cd ~/.vim/plugin/ || ferr "can not cd"
    ln -s ../plugin-available/plugin-configuration-you-complete-me.vim . || ferr
}

enable_coc(){
    cd ~/.vim/pack/plugins/start || ferr "can not cd"
    ln -s ../bundle-available-github/coc.nvim git-coc.nvim || ferr

    cd ~/.vim/plugin/ || ferr "can not cd"
    ln -s ../plugin-available/plugin-configuration-coc.vim . || ferr
}

completer=${1:-ycm}

echo "acivating $completer completion"
disable_all

case $completer in
    ycm)
        enable_ycm
    ;;

    coc)
        enable_coc
    ;;
esac
