#!/bin/bash

ferr(){
    echo "FATAL ERROR: $*"
    exit 1
}

bundle_start="$HOME/.vim/bundles/start"
bundle_avai="../available-github"

conf_used="$HOME/.vim/configuration/used"
conf_avai="../available"

disable_all(){
    rm -f \
        $bundle_start/git-supertab \
        $bundle_start/git-YouCompleteMe \
        $bundle_start/git-coc.nvim \
        $conf_used/plugin-configuration-you-complete-me.vim \
        $conf_used/plugin-configuration-coc.vim
}

enable_ycm(){
    cd $bundle_start || ferr "can not cd"
    ln -s $bundle_avai/supertab git-supertab || ferr

    cd $bundle_start || ferr "can not cd"
    ln -s $bundle_avai/YouCompleteMe git-YouCompleteMe || ferr

    cd $conf_used || ferr "can not cd"
    ln -s $conf_avai/plugin-configuration-you-complete-me.vim . || ferr
}

enable_coc(){
    cd $bundle_start || ferr "can not cd"
    ln -s $bundle_avai/coc.nvim git-coc.nvim || ferr

    cd $conf_used || ferr "can not cd"
    ln -s $conf_avai/plugin-configuration-coc.vim . || ferr
}

completer=${1:-ycm}

echo "acivating $completer completion"
disable_all

case $completer in
    ycm)
        enable_ycm
    ;;

    coc)
        enable_coc
    ;;
esac
