#!/bin/bash
set -uo pipefail

declare -r script="$(readlink -f "${BASH_SOURCE[0]}")"
declare -r script_dir="$(dirname $script)"
. "$script_dir"/library.bash

cd "$script_dir" || ferr "could not cd into script dir"

plugins=(
    https://github.com/ObiWahn/vim-airline.git
    https://github.com/editorconfig/editorconfig-vim.git
    https://github.com/inside/vim-grep-operator
    https://github.com/farmergreg/vim-lastplace
    https://github.com/ctrlpvim/ctrlp.vim
    https://github.com/ycm-core/YouCompleteMe
    https://github.com/scrooloose/nerdtree.git
    https://github.com/nathanaelkane/vim-indent-guides
)

for plugin in "${plugins[@]}"; do
    ./install-github "$plugin"
done
