#!/bin/bash
set -uo pipefail

declare -r script="$(readlink -f "${BASH_SOURCE[0]}")"
declare -r script_dir="$(dirname $script)"
. "$script_dir"/library.bash

cd "$script_dir" || ferr "could not cd into script dir"

plugins=(
    https://github.com/ObiWahn/vim-airline
    https://github.com/editorconfig/editorconfig-vim
    https://github.com/inside/vim-grep-operator
    https://github.com/farmergreg/vim-lastplace
    https://github.com/ctrlpvim/ctrlp.vim
    https://github.com/ycm-core/YouCompleteMe
    https://github.com/scrooloose/nerdtree
    https://github.com/nathanaelkane/vim-indent-guides
    https://github.com/tpope/vim-fugitive
    https://github.com/jremmen/vim-ripgrep
    https://github.com/ervandew/supertab
    https://github.com/junegunn/fzf
    https://github.com/junegunn/fzf.vim
    https://github.com/neoclide/coc.nvim
)

for plugin in "${plugins[@]}"; do
    ./install-github "$plugin"
done
