#!/usr/bin/env bash
set -uo pipefail

script="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script")"
. "$script_dir"/library.bash

# we must be in the start directory
cd "$script_dir" || ferr "could not cd into script dir"

[[ -n $* ]] || { echo "no github_url given"; exit 1; }

github_url="$1"
name="${github_url##*/}"
repo_path="./available-github/$name"

if [[ -d "$repo_path" ]]; then
    echo "$repo_path already exists!"
    exit 0
fi

git clone "$github_url" "$repo_path" || ferr "could not clone"
ln -s "$repo_path" "git-$name" || ferr "could not create github_url"
