#!/usr/bin/env bash
set -uo pipefail

declare -r script="$(readlink -f "${BASH_SOURCE[0]}")"
declare -r script_dir="$(dirname "$script")"
. "$script_dir"/library.bash

plug_dir="./start"

skip=(
        git-vim-airline
        git-YouCompleteMe
     )

for d in "$plug_dir/"* ; do
    [[ -e "$d/.git" ]] || continue
    print "$d"

    for skip_item in "${skip[@]}"; do
        if [[ "$d" == "$plug_dir/$skip_item" ]]; then
            echo "skipping $d"
            continue 2
        fi
    done

    ( \
        cd "$d" && { git fetch  &>/dev/null || { ehco "could not fetch"; exit 1; }; }  && git merge --ff-only @{u} \
    ) \
    || { echo "failed to upgrade $d "; }
done
