#!/usr/bin/env bash
set -uo pipefail

declare -r script="$(readlink -f "${BASH_SOURCE[0]}")"
declare -r script_dir="$(dirname $script)"
. "$script_dir"/library.bash

for dir in * ; do
    if [ -d "$dir/doc" ]; then
        echo "helptags $dir/doc/"
        vim -c "helptags $dir/doc/" -c q
    fi
done
