#!/usr/bin/env bash
set -uo pipefail

declare -r script="$(readlink -f "${BASH_SOURCE[0]}")"
declare -r script_dir="$(dirname "$script")"
. "$script_dir"/library.bash

skip=(
        git-YouCompleteMe
        git-vim-airline
     )

for d in *; do
    [[ -e "$d/.git" ]] || continue
    print "$d"

    for skip_item in "${skip[@]}"; do
        if [[ "$d" == "$skip_item" ]]; then
            echo "skipping $d"
            continue 2
        fi
    done

    ( cd "$d" && git pull || git pull origin master ) || { echo "failed to upgrade $d "; exit 0; }
done
